# Reload-Safe Daemons
exec_always autotiling
exec_always killall -q swaync; swaync
exec_always killall -q swayosd-server; swayosd-server

# System Applets and Authentication
exec udiskie -t
exec nm-applet --indicator
exec blueman-applet
exec /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Clipboard Manager
exec wl-paste --type text --watch cliphist store
exec wl-paste --type image --watch cliphist store

# Idle Management and Screen Locking
exec swayidle -w \
         timeout 600 'swaylock -f' \
         timeout 900 'swaymsg "output * power off"' resume 'swaymsg "output * power on"' \
         before-sleep 'swaylock -f'
