# Floating Window Rules
for_window [window_role="pop-up"] floating enable
for_window [window_role="task_dialog"] floating enable
for_window [app_id="pavucontrol"] floating enable, resize set width 600 px height 400 px
for_window [app_id="blueman-manager"] floating enable, resize set width 600 px height 400 px
for_window [app_id="goverlay"] floating enable
for_window [class="Thunar"] floating enable
for_window [title="Thunar"] floating enable
for_window [window_role="dialog" class="Thunar"] floating enable
for_window [app_id="org.gnome.Calculator"] floating enable
for_window [app_id="file-roller"] floating enable

# Picture-in-Picture Rules
for_window [title="^(Picture-in-Picture|Picture in picture)$"] floating enable, sticky enable, resize set width 600 px height 338 px

# XWayland Video Bridge Hide Rule
for_window [class="xwaylandvideobridge"] {
    floating enable
    max_size 1 1
    move scratchpad
    no_focus
}

# Application-Specific Rules: Steam
for_window [class="[Ss]team" title="Friends List"] floating enable
for_window [class="[Ss]team" title=".* - Chat"] floating enable
assign [class="gamescope"] number 5
for_window [class="gamescope"] fullscreen enable
# Fullscreen Idle Inhibit
for_window [class=".*"] inhibit_idle fullscreen
