default_border pixel 2
gaps inner 7
gaps outer 3

font pango:JetBrainsMono NF 11

# Window colors
# 			title-border	title-background 	title-text	indicator	focused-border
client.focused 		#1a1b26		#414868			#c0caf5		#f7768e		#7aa2f7
client.unfocused	#1a1b26		#32344a			#a9b1d6		#7dcfff		#3d59a1

